"""Initial migration

Revision ID: 1ab18aada64a
Revises: 
Create Date: 2025-06-06 15:36:25.244850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ab18aada64a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_of_lading',
    sa.Column('driver_name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('work_order_no', sa.String(length=50), nullable=True),
    sa.Column('pickup_name', sa.String(length=100), nullable=True),
    sa.Column('pickup_address', sa.String(length=200), nullable=True),
    sa.Column('pickup_city', sa.String(length=100), nullable=True),
    sa.Column('pickup_state', sa.String(length=50), nullable=True),
    sa.Column('pickup_zip', sa.String(length=20), nullable=True),
    sa.Column('pickup_phone', sa.String(length=30), nullable=True),
    sa.Column('delivery_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.String(length=200), nullable=True),
    sa.Column('delivery_city', sa.String(length=100), nullable=True),
    sa.Column('delivery_state', sa.String(length=50), nullable=True),
    sa.Column('delivery_zip', sa.String(length=20), nullable=True),
    sa.Column('delivery_phone', sa.String(length=30), nullable=True),
    sa.Column('condition_codes', sa.String(length=200), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('pickup_agent_name', sa.String(length=100), nullable=True),
    sa.Column('pickup_signature', sa.Text(), nullable=True),
    sa.Column('pickup_date', sa.Date(), nullable=True),
    sa.Column('delivery_agent_name', sa.String(length=100), nullable=True),
    sa.Column('delivery_signature', sa.Text(), nullable=True),
    sa.Column('delivery_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_of_lading_id'), 'bill_of_lading', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('bol_vehicle',
    sa.Column('bill_of_lading_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=10), nullable=True),
    sa.Column('make', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('mileage', sa.String(length=50), nullable=True),
    sa.Column('price', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_of_lading_id'], ['bill_of_lading.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bol_vehicle_id'), 'bol_vehicle', ['id'], unique=False)
    op.create_table('daily_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('diesel_amount', sa.Float(), nullable=False),
    sa.Column('diesel_location', sa.String(), nullable=False),
    sa.Column('def_amount', sa.Float(), nullable=False),
    sa.Column('def_location', sa.String(), nullable=False),
    sa.Column('other_expense_description', sa.String(), nullable=True),
    sa.Column('other_expense_amount', sa.Float(), nullable=True),
    sa.Column('other_expense_location', sa.String(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_expenses_id'), 'daily_expenses', ['id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('car_year', sa.String(), nullable=True),
    sa.Column('car_make', sa.String(), nullable=True),
    sa.Column('car_model', sa.String(), nullable=True),
    sa.Column('car_vin', sa.String(), nullable=True),
    sa.Column('pickup_location', sa.String(), nullable=False),
    sa.Column('dropoff_location', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_daily_expenses_id'), table_name='daily_expenses')
    op.drop_table('daily_expenses')
    op.drop_index(op.f('ix_bol_vehicle_id'), table_name='bol_vehicle')
    op.drop_table('bol_vehicle')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_bill_of_lading_id'), table_name='bill_of_lading')
    op.drop_table('bill_of_lading')
    # ### end Alembic commands ### 