"""add_work_order_payment_tracking

Revision ID: 55ea4e622fde
Revises: de4e2d20f6e7
Create Date: 2025-08-05 13:50:55.042672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ea4e622fde'
down_revision = 'de4e2d20f6e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_of_lading', sa.Column('total_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('work_order_no', sa.String(length=50), nullable=False))
    op.add_column('transactions', sa.Column('collected_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('due_amount', sa.Float(), nullable=False))
    op.add_column('transactions', sa.Column('bol_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'bill_of_lading', ['bol_id'], ['id'])
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'car_vin')
    op.drop_column('transactions', 'car_year')
    op.drop_column('transactions', 'car_make')
    op.drop_column('transactions', 'car_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('car_model', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('car_make', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('car_year', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('car_vin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'bol_id')
    op.drop_column('transactions', 'due_amount')
    op.drop_column('transactions', 'collected_amount')
    op.drop_column('transactions', 'work_order_no')
    op.drop_column('bill_of_lading', 'total_amount')
    # ### end Alembic commands ### 