"""Add broker fields to bill of lading

Revision ID: 895ccc679cdb
Revises: 55ea4e622fde
Create Date: 2025-08-18 12:22:41.655110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '895ccc679cdb'
down_revision = '55ea4e622fde'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_of_lading', sa.Column('broker_name', sa.String(length=100), nullable=True))
    op.add_column('bill_of_lading', sa.Column('broker_address', sa.String(length=200), nullable=True))
    op.add_column('bill_of_lading', sa.Column('broker_phone', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bill_of_lading', 'broker_phone')
    op.drop_column('bill_of_lading', 'broker_address')
    op.drop_column('bill_of_lading', 'broker_name')
    # ### end Alembic commands ### 