name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Frontend Dependencies
      working-directory: ./src
      run: |
        npm ci
        npm run build
      env:
        NEXT_PUBLIC_API_URL: http://${{ secrets.EC2_HOST }}/api

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install "pydantic[email]"
        pip install -r requirements.txt

    - name: Run Backend Tests
      working-directory: ./backend
      run: pytest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          # Function to check if a command exists
          command_exists() {
            command -v "$1" >/dev/null 2>&1
          }

          # Install required packages
          echo "Installing required packages..."
          sudo apt-get update
          sudo apt-get install -y git nodejs npm python3-pip python3-venv nginx

          # Create application directory
          echo "Setting up application directory..."
          sudo mkdir -p /home/ubuntu/ideal-transportation
          sudo chown -R ubuntu:ubuntu /home/ubuntu/ideal-transportation
          cd /home/ubuntu/ideal-transportation

          # Clean up existing directory
          echo "Cleaning up existing directory..."
          rm -rf * .[^.]*

          # Clone repository using REPO_URL secret
          echo "Cloning repository..."
          git clone ${{ secrets.REPO_URL }} .
          if [ $? -ne 0 ]; then
            echo "Git clone failed. Current directory contents:"
            ls -la
            exit 1
          fi

          # Verify repository contents
          echo "Verifying repository contents..."
          ls -la
          echo "Checking git status..."
          git status

          # Setup backend
          echo "Setting up backend..."
          cd backend
          
          # Remove existing venv if it exists
          rm -rf venv
          
          # Create virtual environment
          python3 -m venv venv
          
          # Activate virtual environment and install dependencies
          source venv/bin/activate
          pip install --upgrade pip
          pip install "pydantic[email]"
          pip install -r requirements.txt
          pip install uvicorn

          # Verify Python and uvicorn installation
          echo "Verifying Python installation..."
          which python
          python --version
          echo "Verifying uvicorn installation..."
          which uvicorn
          uvicorn --version

          # Create environment file
          echo "Creating environment file..."
          sudo tee /home/ubuntu/ideal-transportation/backend/.env << EOF
          DATABASE_URL=${{ secrets.DATABASE_URL }}
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          EOF

          # Setup systemd service
          echo "Setting up systemd service..."
          sudo tee /etc/systemd/system/ideal-transportation.service << 'EOF'
          [Unit]
          Description=Ideal Transportation Backend
          After=network.target

          [Service]
          User=ubuntu
          Group=ubuntu
          WorkingDirectory=/home/ubuntu/ideal-transportation/backend
          Environment="PATH=/home/ubuntu/ideal-transportation/backend/venv/bin"
          Environment="DATABASE_URL=${{ secrets.DATABASE_URL }}"
          Environment="SECRET_KEY=${{ secrets.SECRET_KEY }}"
          ExecStart=/home/ubuntu/ideal-transportation/backend/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
          Restart=always
          StandardOutput=append:/var/log/ideal-transportation.log
          StandardError=append:/var/log/ideal-transportation.error.log

          [Install]
          WantedBy=multi-user.target
          EOF

          # Create log files and set permissions
          sudo touch /var/log/ideal-transportation.log /var/log/ideal-transportation.error.log
          sudo chown ubuntu:ubuntu /var/log/ideal-transportation.log /var/log/ideal-transportation.error.log

          # Enable and restart service
          sudo systemctl daemon-reload
          sudo systemctl enable ideal-transportation
          sudo systemctl restart ideal-transportation

          # Wait for service to start and check status
          sleep 5
          echo "Checking service status..."
          sudo systemctl status ideal-transportation
          echo "Checking service logs..."
          sudo tail -n 50 /var/log/ideal-transportation.log
          echo "Checking error logs..."
          sudo tail -n 50 /var/log/ideal-transportation.error.log

          # Test backend directly
          echo "Testing backend directly..."
          curl -v http://localhost:8000/health

          # Setup frontend
          echo "Setting up frontend..."
          cd ../src
          npm ci
          npm run build

          # Fix frontend permissions
          echo "Setting up frontend permissions..."
          sudo chown -R www-data:www-data /home/ubuntu/ideal-transportation/src/out
          sudo chmod -R 755 /home/ubuntu/ideal-transportation/src/out
          sudo chmod -R 755 /home/ubuntu/ideal-transportation/src/out/index.html

          # Verify frontend files
          echo "Verifying frontend files..."
          ls -la /home/ubuntu/ideal-transportation/src/out

          # Setup nginx
          echo "Setting up nginx..."
          sudo tee /etc/nginx/sites-available/ideal-transportation << 'EOF'
          server {
              listen 80;
              server_name _;  # Accepts any hostname/IP

              # Frontend
              location / {
                  root /home/ubuntu/ideal-transportation/src/out;
                  try_files $uri $uri/ /index.html;
                  add_header Cache-Control "no-cache";
              }

              # Backend API
              location /api/ {
                  proxy_pass http://localhost:8000/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              # Error logs
              error_log /var/log/nginx/ideal-transportation.error.log;
              access_log /var/log/nginx/ideal-transportation.access.log;
          }
          EOF

          # Enable nginx site
          sudo ln -sf /etc/nginx/sites-available/ideal-transportation /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t
          sudo systemctl restart nginx

          # Check nginx logs
          echo "Checking nginx logs..."
          sudo tail -n 50 /var/log/nginx/error.log
          sudo tail -n 50 /var/log/nginx/ideal-transportation.error.log

          # Test nginx configuration
          echo "Testing nginx configuration..."
          curl -v http://localhost/health
          curl -v http://localhost/

          # Final status check
          echo "Final status check..."
          sudo systemctl status ideal-transportation
          sudo systemctl status nginx
          ps aux | grep uvicorn
          netstat -tulpn | grep -E ':(80|8000)'

          echo "Deployment completed successfully!"

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }} 