name: Deploy to EC2

# This workflow will deploy the application to EC2
# Last updated: 2024-06-14

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Frontend Dependencies
      working-directory: ./
      run: |
        npm ci
        npm run build
        ls -la .next/  # Verify build output
      env:
        NEXT_PUBLIC_API_URL: http://${{ secrets.EC2_HOST }}/api

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Backend Dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install "pydantic[email]"
        pip install -r requirements.txt

    - name: Run Backend Tests
      working-directory: ./backend
      run: pytest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Check EC2 Instance Status
      run: |
        echo "Checking EC2 instance status..."
        aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].[InstanceId,PublicIpAddress,State.Name,SecurityGroups[*].GroupId]" --output table
        
        echo "Checking instance security groups..."
        INSTANCE_ID=$(aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[*].Instances[*].[InstanceId]" --output text)
        if [ ! -z "$INSTANCE_ID" ]; then
          echo "Found instance: $INSTANCE_ID"
          aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].SecurityGroups[*].[GroupId,GroupName]" --output table
          
          echo "Checking security group rules..."
          SG_ID=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query "Reservations[*].Instances[*].SecurityGroups[*].GroupId" --output text)
          if [ ! -z "$SG_ID" ]; then
            aws ec2 describe-security-groups --group-ids $SG_ID --query "SecurityGroups[*].IpPermissions[*].[FromPort,ToPort,IpRanges[*].CidrIp]" --output table
          else
            echo "No security group found for instance"
          fi
        else
          echo "No running instances found"
        fi

    - name: Test SSH Connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          echo "Testing SSH connection..."
          whoami
          pwd
          hostname

    - name: Setup Application Directory
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          echo "Setting up application directory..."
          sudo apt-get update
          sudo apt-get install -y git nodejs npm python3-pip python3-venv nginx
          sudo mkdir -p /home/ubuntu/ideal-transportation
          sudo chown -R ubuntu:ubuntu /home/ubuntu/ideal-transportation
          cd /home/ubuntu/ideal-transportation
          rm -rf * .[^.]*

    - name: Clone Repository
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          cd /home/ubuntu/ideal-transportation
          git clone ${{ secrets.REPO_URL }} .
          ls -la

    - name: Setup Backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          # Create necessary directories
          sudo mkdir -p /var/log/ideal-transportation
          sudo chown -R ubuntu:ubuntu /var/log/ideal-transportation
          sudo chmod -R 755 /var/log/ideal-transportation
          
          # Create and configure virtual environment
          cd /home/ubuntu/ideal-transportation/backend
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install "sqlalchemy>=2.0.0"
          pip install -r requirements.txt
          
          # Create environment file
          cat > .env << EOL
          DATABASE_URL=postgresql://idealtransport:idealtransport19041988@idealtransport.cvyuacwgotuv.ap-southeast-2.rds.amazonaws.com:5432/idealtransport
          SECRET_KEY=your-secret-key-here
          LOG_DIR=/var/log/ideal-transportation
          EOL
          
          # Create systemd service file
          sudo tee /etc/systemd/system/ideal-transportation.service << EOL
          [Unit]
          Description=Ideal Transportation Backend
          After=network.target
          
          [Service]
          User=ubuntu
          Group=ubuntu
          WorkingDirectory=/home/ubuntu/ideal-transportation/backend
          Environment="PATH=/home/ubuntu/ideal-transportation/backend/venv/bin"
          Environment="DATABASE_URL=postgresql://idealtransport:idealtransport19041988@idealtransport.cvyuacwgotuv.ap-southeast-2.rds.amazonaws.com:5432/idealtransport"
          Environment="SECRET_KEY=your-secret-key-here"
          Environment="LOG_DIR=/var/log/ideal-transportation"
          ExecStart=/home/ubuntu/ideal-transportation/backend/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 --log-level debug
          Restart=always
          
          [Install]
          WantedBy=multi-user.target
          EOL
          
          # Reload systemd and start service
          sudo systemctl daemon-reload
          sudo systemctl enable ideal-transportation
          sudo systemctl restart ideal-transportation

    - name: Setup Frontend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          # Create frontend directory
          sudo mkdir -p /home/ubuntu/ideal-transportation/.next
          sudo chown -R ubuntu:ubuntu /home/ubuntu/ideal-transportation/.next

    - name: Copy Frontend Build
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        source: ".next/"
        target: "/home/ubuntu/ideal-transportation/.next"
        strip_components: 1

    - name: Set Frontend Permissions
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          # Fix frontend permissions
          sudo chown -R www-data:www-data /home/ubuntu/ideal-transportation/.next
          sudo chmod -R 755 /home/ubuntu/ideal-transportation/.next
          
          # Verify frontend files
          ls -la /home/ubuntu/ideal-transportation/.next

    - name: Setup Nginx
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          # Setup nginx
          sudo tee /etc/nginx/sites-available/ideal-transportation << 'EOF'
          server {
              listen 80;
              server_name _;  # Accepts any hostname/IP

              # Frontend
              location / {
                  root /home/ubuntu/ideal-transportation/src/out;
                  try_files $uri $uri/ /index.html;
                  add_header Cache-Control "no-cache";
              }

              # Backend API
              location /api/ {
                  proxy_pass http://localhost:8000/;
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              # Error logs
              error_log /var/log/nginx/ideal-transportation.error.log;
              access_log /var/log/nginx/ideal-transportation.access.log;
          }
          EOF

          # Enable nginx site
          sudo ln -sf /etc/nginx/sites-available/ideal-transportation /etc/nginx/sites-enabled/
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo nginx -t
          sudo systemctl restart nginx

    - name: Verify Deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 60s
        command_timeout: 30m
        debug: true
        script: |
          # Check service status
          sudo systemctl status ideal-transportation
          sudo systemctl status nginx
          
          # Check logs
          sudo tail -n 50 /var/log/ideal-transportation.log
          sudo tail -n 50 /var/log/ideal-transportation.error.log
          sudo tail -n 50 /var/log/nginx/error.log
          
          # Test endpoints
          curl -v http://localhost:8000/health
          curl -v http://localhost/
          
          # Check processes
          ps aux | grep uvicorn
          netstat -tulpn | grep -E ':(80|8000)'

    env:
      DATABASE_URL: postgresql://idealtransport:idealtransport19041988@idealtransport.cvyuacwgotuv.ap-southeast-2.rds.amazonaws.com:5432/idealtransport
      SECRET_KEY: your-secret-key-here 